
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plnanpjacxzazwnwyavw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbmFucGphY3h6YXp3bnd5YXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNDMzMjksImV4cCI6MjA1NjgxOTMyOX0.alVYD6sxrJvmlD8uR1VvJA8kASfWvSDSncVz4u4FvD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
